### ISSUE TITLE
there's no such thing as h element

### ISSUE THREAD

**Issue by fountainpen** [rudransh61/NextGenCSS-#1]
there are h1, h2, h3, h4 , h5 and h6

all have diffferent sizes. there's no such thing as just h

**Comment by rudransh61** [comment]
thanks for your suggestion we will work on or you can make a pull request.

**Comment by rudransh61** [comment]
If you want to contribute you can write here

**Comment by fountainpen** [comment]
you should fix your own coding mistakes, since you wrote it

**Comment by rudransh61** [comment]
solved !!

**Comment by fountainpen** [comment]
elements dont need classes. 
I thought you know css
