### ISSUE TITLE
do you take a look at ffinished css file?

### ISSUE THREAD

**Issue by fountainpen** [rudransh61/NextGenCSS-#10]
you have repetitions all over the place

- font call repetitions
- html twice - this line you dont need coz its default:
```
html {
  font-size: 16px; }

```

- no such thing as 
```
text {
  font-family: "Poppins", sans-serif; }
```
there is **span** however and **mark** which you didnt define, but you should.

**Comment by rudransh61** [comment]
I will work on that ,
and i had added html {fontsize:16} if it is not provided as default in some xyz browser
