### ISSUE TITLE
no button-rect

### ISSUE THREAD

**Issue by fountainpen** [rudransh61/NextGenCSS-#9]
here's an idea

don't put any .button-rect class. delete that

**instead make that style for default button element**

and on hover instead of being white make text lightblue

**Comment by rudransh61** [comment]
But we have 2 types of buttons , button-rect with rectangular corners and button-curve with curved borders,  so it will make confusing to use button or button-rect . Button-rect is more readable and can be understand only by the name.

Yes we can add another class , for a button (in./elements) for default button

**Comment by fountainpen** [comment]
you dont need class at all

`.button-rec` should be just `button` 

and this will be default.

if anyone wants curve  then one will use class for it.

**Comment by rudransh61** [comment]
You can make  a pull request , or I will complete it in 1 week

**Comment by rudransh61** [comment]
done
